
import streamlit as st
import pandas as pd

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak
)

from reportlab.lib.styles import (
    getSampleStyleSheet
)

from datetime import datetime

st.title("📄 Report Generator")

df = pd.read_csv("data/assignments.csv")
exam_df = pd.read_csv("data/exams.csv")

if st.button("Generate PDF Report"):

    pdf_file = "StudyMate_Report.pdf"

    styles = getSampleStyleSheet()

    content = []

    total_assignments = len(df)

    upcoming_exams = len(exam_df)

    if "Priority" in df.columns:

        urgent_tasks = len(
            df[df["Priority"] == "🔴 High"]
        )

    else:

        urgent_tasks = 0

    productivity_score = max(
        0,
        100 - urgent_tasks * 15
    )

    doc = SimpleDocTemplate(pdf_file)

    # =====================
    # COVER PAGE
    # =====================

    content.append(
        Paragraph(
            "🎓 StudyMate AI Pro",
            styles["Title"]
        )
    )

    content.append(
        Spacer(1, 20)
    )

    content.append(
        Paragraph(
            "Student Productivity Report",
            styles["Heading1"]
        )
    )

    content.append(
        Spacer(1, 20)
    )

    content.append(
        Paragraph(
            f"Generated On: {datetime.now().strftime('%d-%m-%Y %H:%M')}",
            styles["Normal"]
        )
    )

    content.append(
        Spacer(1, 30)
    )

    content.append(
        Paragraph(
            "AI Powered Academic Productivity Platform",
            styles["Italic"]
        )
    )

    content.append(
        PageBreak()
    )

    # =====================
    # KPI SUMMARY
    # =====================

    content.append(
        Paragraph(
            "📊 Productivity Summary",
            styles["Heading1"]
        )
    )

    content.append(
        Spacer(1, 15)
    )

    content.append(
        Paragraph(
            f"Total Assignments: {total_assignments}",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            f"Upcoming Exams: {upcoming_exams}",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            f"Urgent Tasks: {urgent_tasks}",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            f"Productivity Score: {productivity_score}/100",
            styles["Normal"]
        )
    )

    content.append(
        Spacer(1, 20)
    )

    # =====================
    # ASSIGNMENTS
    # =====================

    content.append(
        Paragraph(
            "📚 Assignment Details",
            styles["Heading2"]
        )
    )

    content.append(
        Spacer(1, 10)
    )

    for _, row in df.iterrows():

        subject = row.get("Subject", "N/A")
        task = row.get("Task", "N/A")

        content.append(
            Paragraph(
                f"• {subject} - {task}",
                styles["Normal"]
            )
        )

    content.append(
        Spacer(1, 20)
    )

    # =====================
    # EXAMS
    # =====================

    content.append(
        Paragraph(
            "📝 Upcoming Exams",
            styles["Heading2"]
        )
    )

    content.append(
        Spacer(1, 10)
    )

    for _, row in exam_df.iterrows():

        subject = row.get("Subject", "N/A")
        exam_date = row.get("ExamDate", "N/A")

        content.append(
            Paragraph(
                f"• {subject} : {exam_date}",
                styles["Normal"]
            )
        )

    content.append(
        Spacer(1, 30)
    )

    # =====================
    # FOOTER
    # =====================

    content.append(
        Paragraph(
            "Generated by StudyMate AI Pro",
            styles["Heading3"]
        )
    )

    content.append(
        Paragraph(
            "Built using Streamlit, Gemini AI, Data Analytics and Productivity Tracking",
            styles["Italic"]
        )
    )

    doc.build(content)

    with open(pdf_file, "rb") as file:

        st.download_button(
            "⬇ Download PDF Report",
            file,
            file_name=pdf_file,
            mime="application/pdf"
        )

